name: Build & Deploy to Nekoweb and Neocities

on: [push]

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-nekoweb
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Fetch all history for git info
      - name: "Use node version"
        uses: actions/setup-node@v3
        with:
            cache: 'npm'
      - name: "Install dependencies"
        run: npm install
      - name: "Build"
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: n-sites
          path: notes
          retention-days: 7
  neko-deploy:
    name: Deploy to neko
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: n-sites
          path: notes
      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@main
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-cookie: ${{ secrets.NEKOWEB_COOKIE }}
          nekoweb-domain: 'medjedsdigitalgarden.nekoweb.org'
          nekoweb-username: 'mustarddayart'
          directory: 'notes'
      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v3
        with:
          api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: false
          neocities_supporter: false # set this to true if you have a supporter account and want to bypass unsuported files filter.
          preview_before_deploy: true # print a deployment plan prior to waiting for files to upload.
          dist_dir: notes
